ebean:
  dbSchema: test_app  # use this schema rather than public for postgresql
  migration:
    run: true       # run database migrations on startup


datasource:
  db:
    username: sa
    password: sa
    url: jdbc:h2:mem:testapp

#  other:
#    username: other_username
#    password: ${otherPassword}
#    url: jdbc:postgresql://${otherDatabaseHost}:5432/other_dbname