spring:
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./fluent-ai
    hikari:
      username: fluent-ai
      password: fluent-ai
    username: fluent-ai
    password: fluent-ai
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect